name: Backup Neon to Telegram

on:
  workflow_dispatch:

  schedule:
    - cron: "0 19 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Check PostgreSQL Version
        run: |
          docker run --rm postgres:17 pg_dump --version

      - name: Create Backup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          FILE_NAME="neon-$(date +'%Y-%m-%d_%H-%M').dump"

          docker run --rm \
            -e DATABASE_URL="$DATABASE_URL" \
            -v "$PWD:/backup" \
            postgres:17 \
            bash -c "pg_dump -Fc \"\$DATABASE_URL\" -f /backup/$FILE_NAME"

          gzip "$FILE_NAME"

          echo "BACKUP_FILE=${FILE_NAME}.gz" >> $GITHUB_ENV

      - name: Send Backup to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s \
            -F chat_id="$CHAT_ID" \
            -F document=@"$BACKUP_FILE" \
            -F caption="✅ Backup Neon berhasil $(date)" \
            "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument"

      - name: Send Failure Notification
        if: failure()
        env:
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s \
            -X POST \
            "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d text="❌ Backup Neon gagal pada workflow ${{ github.workflow }}"
